### ISSUE TITLE
Have to keep the button on toolbar

### ISSUE THREAD

**Issue by wenisy** [radpet/ckeditor-dropdownmenumanager#5]
I have to keep `JustifyCenter` buttons on toolbar, or dropdownmenu could not work.

![image](https://user-images.githubusercontent.com/5832130/61277875-a2ab5e80-a7e5-11e9-84f2-69a90e08e6a0.png)

How to hide the buttons which already existed in dropdownmenu?

![image](https://user-images.githubusercontent.com/5832130/61277916-b6ef5b80-a7e5-11e9-9358-cd700be78937.png)

**Comment by wenisy** [comment]
Not sure you are still maintanence it....

I'm using `ckeditor 4.12.1`

**Comment by radpet** [comment]
I do apologise but I no longer support any ckeditor plugins.
Nothing comes to mind about this issue.
